allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  lefthook: true
  lmdb: true
  msgpackr-extract: true
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - lefthook
  - lmdb
  - msgpackr-extract
