name: Setup Workspace
description: 'Sets up environment installs dependencies for the projects.'

runs:
  using: 'composite'
  steps:
    - name: Install Node.js
      uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
      with:
        node-version-file: '.nvmrc'
        cache: 'pnpm'
        cache-dependency-path: 'pnpm-lock.yaml'

    - name: Enable pnpm via Corepack
      shell: bash
      run: |
        corepack enable
        PNPM_VERSION=$(node -p "require('./package.json').packageManager?.split('@')[1] || ''")
        if [ -n "$PNPM_VERSION" ]; then
          corepack prepare "pnpm@$PNPM_VERSION" --activate
        else
          corepack install
        fi
        pnpm --version

    - name: Setup Angular build cache
      uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5
      with:
        path: .angular/cache
        key: ${{ runner.os }}-angular-cache-${{ hashFiles('angular.json', 'pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-angular-cache-

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile --prefer-offline
