name: Setup Workspace
description: 'Sets up environment installs dependencies for the projects.'

runs:
  using: 'composite'
  steps:
    - name: Install Node.js
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
      with:
        node-version-file: '.nvmrc'

    - name: Enable pnpm via Corepack
      shell: bash
      run: |
        corepack enable
        corepack install
        pnpm --version

    - name: Get pnpm store directory
      shell: bash
      id: pnpm-cache
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

    - name: Setup pnpm cache
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('package.json') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}-
          ${{ runner.os }}-pnpm-

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
