name: Build Action
description: 'This action will build the application'

inputs:
  base-href:
    description: 'Base href for the application'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Create Angular cache directory
      shell: bash
      run: mkdir -p .angular/cache

    - name: Restore Angular build cache
      uses: actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5
      with:
        path: .angular/cache
        key: ${{ runner.os }}-angular-${{ hashFiles('**/pnpm-lock.yaml', 'angular.json', 'tsconfig*.json') }}
        restore-keys: |
          ${{ runner.os }}-angular-

    - name: Setup environment
      uses: ./.github/actions/workspace-setup-action

    - name: Run build
      shell: bash
      run: |
        if [ -n "${{ inputs.base-href }}" ]; then
          pnpm run build --base-href=${{ inputs.base-href }}
        else
          pnpm run build
        fi
