name: Build Action
description: 'This action will build the application'

runs:
  using: 'composite'
  steps:
    - name: Setup environment
      uses: ./.github/actions/workspace-setup-action
    - name: Run build
      shell: bash
      run: pnpm run build
