name: Build Action
description: 'This action will build the application'

inputs:
  base-href:
    description: 'Base href for the application'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Setup environment
      uses: ./.github/actions/workspace-setup-action
    - name: Run build
      shell: bash
      run: |
        if [ -n "${{ inputs.base-href }}" ]; then
          pnpm run build --base-href=${{ inputs.base-href }}
        else
          pnpm run build
        fi
