name: Deploy Preview
description: 'Deploys build to GH Pages preview subfolder and posts a PR comment with the URL.'

inputs:
  repo-name:
    description: 'GitHub repository name'
    required: true
  repo-owner:
    description: 'GitHub repository owner'
    required: true
  pr-number:
    description: 'Pull request number'
    required: true
  pr-updated-at:
    description: 'Pull request updated_at timestamp'
    required: true
  gh-pages-token:
    description: 'Token with write access to gh-pages branch'
    required: true
  github-token:
    description: 'GitHub token for posting PR comment'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Patch base href
      shell: bash
      run: |
        BASE_HREF="/${{ inputs.repo-name }}/previews/pr-${{ inputs.pr-number }}/"
        find build-output -name "index.html" -exec sed -i "s|<base href=\"/\">|<base href=\"${BASE_HREF}\">|g" {} +
        if ! grep -qr "${BASE_HREF}" build-output; then
          echo "::error::base href patch failed — pattern '<base href=\"/\">' not found in any index.html"
          exit 1
        fi

    - name: Deploy to GH Pages
      uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4
      with:
        folder: build-output
        target-folder: previews/pr-${{ inputs.pr-number }}
        branch: gh-pages
        clean: false
        commit-message: 'docs: deploy preview for PR #${{ inputs.pr-number }}'
        token: ${{ inputs.gh-pages-token }}
        git-config-name: github-actions[bot]
        git-config-email: github-actions[bot]@users.noreply.github.com

    - name: Post preview URL as PR comment
      uses: marocchino/sticky-pull-request-comment@773744901bac0e8cbb5a0dc842800d45e9b2b405 # v2
      with:
        number: ${{ inputs.pr-number }}
        header: preview
        GITHUB_TOKEN: ${{ inputs.github-token }}
        message: |
          ### Preview

          [https://${{ inputs.repo-owner }}.github.io/${{ inputs.repo-name }}/previews/pr-${{ inputs.pr-number }}/](https://${{ inputs.repo-owner }}.github.io/${{ inputs.repo-name }}/previews/pr-${{ inputs.pr-number }}/)

          ---
          *Last updated: ${{ inputs.pr-updated-at }}*
