name: Lighthouse Report
description: 'Runs Lighthouse CI and posts results as a PR comment.'

inputs:
  config-path:
    description: 'Path to the Lighthouse CI config file'
    required: false
    default: '.lighthouserc.cjs'
  github-token:
    description: 'GitHub token for posting the PR comment'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Run Lighthouse CI
      uses: treosh/lighthouse-ci-action@fcd65974f7c4c2bf0ee9d09b84d2489183c29726 # v12.6.1
      with:
        configPath: ${{ inputs.config-path }}
        temporaryPublicStorage: true

    - name: Format Lighthouse results
      id: format
      uses: ./.github/actions/lighthouse/format

    - name: Comment PR with results
      uses: marocchino/sticky-pull-request-comment@773744901bac0e8cbb5a0dc842800d45e9b2b405 # v2
      with:
        header: lighthouse
        GITHUB_TOKEN: ${{ inputs.github-token }}
        message: |
          ## Lighthouse CI Results

          ### Accessibility Score

          | Score | Status | Threshold |
          |:-----:|:------:|:---------:|
          | **${{ steps.format.outputs.accessibility }}%** | ${{ steps.format.outputs.a11y_pass }} | ≥ 95% |

          ### All Categories

          | Category | Score | Status |
          |----------|:-----:|:------:|
          | Performance | **${{ steps.format.outputs.performance }}%** | ${{ steps.format.outputs.perf_status }} |
          | Accessibility | **${{ steps.format.outputs.accessibility }}%** | ${{ steps.format.outputs.a11y_status }} |
          | Best Practices | **${{ steps.format.outputs.best_practices }}%** | ${{ steps.format.outputs.bp_status }} |
          | SEO | **${{ steps.format.outputs.seo }}%** | ${{ steps.format.outputs.seo_status }} |

          > **Thresholds:** Performance ≥90%, Accessibility ≥95%, Best Practices ≥95%, SEO ≥95%

          ${{ steps.format.outputs.public_url && format('**[View Full Lighthouse Report →]({0})**', steps.format.outputs.public_url) || '' }}
